Closes #9 by adding the erase and cleanup commands and refactoring remove as a workflow.

diff --git a/commands/cleanup/script b/commands/cleanup/script
--- a/commands/cleanup/script
+++ b/commands/cleanup/script
@@ -1,11 +1,11 @@
 #!/usr/bin/env bash
 #
-#/ command: mysql:remove: "Remove the MySQL installation from the system"
+#/ command: mysql:cleanup: "Remove database files and logs from the system"
 #
-#/ usage: rerun mysql:remove [ --cleanup <false>] 
+#/ usage: rerun mysql:cleanup [options]
 #
 #/ rerun env variables: RERUN, RERUN_VERSION, RERUN_MODULES, RERUN_MODULE_DIR
-#/ option variables: CLEANUP
+#/ option variables: 
 
 # Read module function library.
 . $RERUN_MODULE_DIR/lib/functions.sh || { 
@@ -17,12 +17,12 @@
 # * Trap calls `rerun_die` with standard message.
 # * Exit upon command errors or accessing unset variables.
 #   * See [set](http://ss64.com/bash/set.html)
-trap 'rerun_die "*** command failed: mysql:remove. ***"' ERR
+trap 'rerun_die "*** command failed: mysql:cleanup. ***"' ERR
 set -o nounset -o pipefail
 
 # Parse the command options.
-[[ -r $RERUN_MODULE_DIR/commands/remove/options.sh ]] && {
-    . $RERUN_MODULE_DIR/commands/remove/options.sh || rerun_die "Failed loading options parser."
+[[ -r $RERUN_MODULE_DIR/commands/cleanup/options.sh ]] && {
+    . $RERUN_MODULE_DIR/commands/cleanup/options.sh || rerun_die "Failed loading options parser."
     rerun_options_parse "$@"
 }
 
@@ -31,17 +31,8 @@ set -o nounset -o pipefail
 # Your implementation goes here.
 # ------------------------------
 
-# Stop the MySQL server:
-rerun mysql:stop
-
-# Remove the MySQL server package and its dependencies from the system:
-rerun mysql:erase
-
-# Cleanup remaining files, if required:
-if [[ $CLEANUP = "true" ]]
-then
-  rerun mysql:cleanup
-fi
+sudo rm -rf /var/lib/mysql
+sudo rm -f /var/log/mysqld.log.rpmsave
 
 exit $?
 
